set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR ARM)

# ARM_TOOLCHAIN_DIR가 정의되지 않은 경우 기본값 설정
if(NOT DEFINED ARM_TOOLCHAIN_DIR)
    set(ARM_TOOLCHAIN_DIR D:/tool/gcc-arm-none-eabi-10.3-2021.10/bin)
endif()

set(BINUTILS_PATH ${ARM_TOOLCHAIN_DIR})

# 경로와 접두사 분리
set(TOOLCHAIN_PREFIX arm-none-eabi-)
set(TOOLCHAIN_PATH ${ARM_TOOLCHAIN_DIR}/)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

# 컴파일러 경로를 명확하게 지정
set(CMAKE_C_COMPILER "${TOOLCHAIN_PATH}${TOOLCHAIN_PREFIX}gcc.exe" CACHE FILEPATH "C Compiler path")
set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_PATH}${TOOLCHAIN_PREFIX}g++.exe" CACHE FILEPATH "C++ Compiler path")

# 확장자 추가(.exe)
set(CMAKE_OBJCOPY "${TOOLCHAIN_PATH}${TOOLCHAIN_PREFIX}objcopy.exe" CACHE INTERNAL "objcopy tool")
set(CMAKE_SIZE_UTIL "${TOOLCHAIN_PATH}${TOOLCHAIN_PREFIX}size.exe" CACHE INTERNAL "size tool")

set(CMAKE_C_STANDARD 11)
set(CMAKE_CXX_STANDARD 17)

set(CMAKE_C_COMPILER_FORCED TRUE)
set(CMAKE_CXX_COMPILER_FORCED TRUE)

set(CMAKE_FIND_ROOT_PATH ${BINUTILS_PATH})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
